[package]
name = "nextgcore-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "NextGCore Core Utilities Library"

[dependencies]
log.workspace = true
thiserror.workspace = true
bytes.workspace = true
bitflags.workspace = true
libc.workspace = true
env_logger.workspace = true
rand.workspace = true
uuid.workspace = true
tokio = { workspace = true, features = ["time", "sync", "rt"] }

[dev-dependencies]
proptest.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
